spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: default_path_to_http
#          uri: https://windmt.com
#          order: 10000
#          predicates:
#            - Path=/**
#          filters:
#            - SetPath=/
server:
  port: 10000
  environment: prod1


eureka:
  instance:
    prefer-ip-address: true
    # instance-id: http://localhost:10000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7003/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
