server:
  # port: 7000
  port: ${PORT:8761}
  # servlet:
  #   context-path: /eureka
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false #以IP地址注册到服务中心，相互注册使用IP地址
    lease-renewal-interval-in-seconds: 10
    #ip-address: 192.168.1.1 #强制指定IP地址，默认会获取本机的IP地址
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://peer1:7000/eureka/
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false


spring:
  boot:
    admin:
      context-path: /admin
  application:
    name: eureka-server
